---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-fbdownloader-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: {{ .Values.configSecret.secretStoreKind }}
    name: {{ .Values.configSecret.secretStore }}
  target:
    name: {{ .Values.name }}-fbdownloader-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: settings.json
      remoteRef:
        key: {{ .Values.configSecret.secretName }}
        property: JSON_CONFIG
        decodingStrategy: Base64
